name: CI

on:
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - run: apt list --installed
      - uses: browser-actions/setup-chrome@v1
        id: setup-chrome
        with:
          chrome-version: 128
      - run: ${{ steps.setup-chrome.outputs.chrome-path }} --version
